-- MySQL Script generated by MySQL Workbench
-- Wed Aug 19 10:51:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospital_aula2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital_aula2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital_aula2` DEFAULT CHARACTER SET utf8 ;
USE `hospital_aula2` ;

-- -----------------------------------------------------
-- Table `hospital_aula2`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_aula2`.`paciente` (
  `id_paciente` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NULL,
  `rg` VARCHAR(45) NULL,
  `sexo` CHAR(1) NULL,
  `data_nascimento` DATE NOT NULL,
  `endereco_completo` VARCHAR(255) NULL,
  `telefone_celular` VARCHAR(15) NOT NULL,
  `telefone_residencial` VARCHAR(15) NULL,
  `telefone_comercial` VARCHAR(15) NULL,
  `nome_convenio` VARCHAR(50) NULL,
  `matricula_convenio` VARCHAR(30) NULL,
  PRIMARY KEY (`id_paciente`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_aula2`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_aula2`.`medico` (
  `idmedico` INT NOT NULL AUTO_INCREMENT,
  `nome_medico` VARCHAR(45) NOT NULL,
  `crm` INT NOT NULL,
  PRIMARY KEY (`idmedico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_aula2`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_aula2`.`consulta` (
  `id_consulta` INT NOT NULL,
  `id_paciente` INT NOT NULL,
  PRIMARY KEY (`id_consulta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital_aula2`.`paciente_has_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital_aula2`.`paciente_has_consulta` (
  `paciente_id_paciente` INT NOT NULL,
  `consulta_id_consulta` INT NOT NULL,
  PRIMARY KEY (`paciente_id_paciente`, `consulta_id_consulta`),
  INDEX `fk_paciente_has_consulta_consulta1_idx` (`consulta_id_consulta` ASC) VISIBLE,
  INDEX `fk_paciente_has_consulta_paciente_idx` (`paciente_id_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_paciente_has_consulta_paciente`
    FOREIGN KEY (`paciente_id_paciente`)
    REFERENCES `hospital_aula2`.`paciente` (`id_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_paciente_has_consulta_consulta1`
    FOREIGN KEY (`consulta_id_consulta`)
    REFERENCES `hospital_aula2`.`consulta` (`id_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
